export const ADD_ITEM_CAROUSEL_REQUEST = 'ADD_ITEM_CAROUSEL_REQUEST'
export const ADD_ITEM_CAROUSEL_SUCCESS = 'ADD_ITEM_CAROUSEL_SUCCESS'
export const ADD_ITEM_CAROUSEL_FAIL = 'ADD_ITEM_CAROUSEL_FAIL'

export const GET_ITEM_CAROUSEL_REQUEST = 'GET_ITEM_CAROUSEL_REQUEST'
export const GET_ITEM_CAROUSEL_SUCCESS = 'GET_ITEM_CAROUSEL_SUCCESS'
export const GET_ITEM_CAROUSEL_FAIL = 'GET_ITEM_CAROUSEL_FAIL'

export const GET_ONE_ITEM_CAROUSEL_REQUEST = 'GET_ONE_ITEM_CAROUSEL_REQUEST'
export const GET_ONE_ITEM_CAROUSEL_SUCCESS = 'GET_ONE_ITEM_CAROUSEL_SUCCESS'
export const GET_ONE_ITEM_CAROUSEL_FAIL = 'GET_ONE_ITEM_CAROUSEL_FAIL'

export const UPDATE_ITEM_CAROUSEL_REQUEST = 'UPDATE_ITEM_CAROUSEL_REQUEST'
export const UPDATE_ITEM_CAROUSEL_SUCCESS = 'UPDATE_ITEM_CAROUSEL_SUCCESS'
export const UPDATE_ITEM_CAROUSEL_FAIL = 'UPDATE_ITEM_CAROUSEL_FAIL'
export const UPDATE_ITEM_CAROUSEL_RESET = 'UPDATE_ITEM_CAROUSEL_RESET'

export const DELETE_ITEM_CAROUSEL_REQUEST = 'DELETE_ITEM_CAROUSEL_REQUEST'
export const DELETE_ITEM_CAROUSEL_SUCCESS = 'DELETE_ITEM_CAROUSEL_SUCCESS'
export const DELETE_ITEM_CAROUSEL_FAIL = 'DELETE_ITEM_CAROUSEL_FAIL'
