export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'
export const GET_ORDER_RESET = 'GET_ORDER_RESET'

export const DELETE_ORDER_BY_ID_REQUEST = 'DELETE_ORDER_BY_ID_REQUEST'
export const DELETE_ORDER_BY_ID_SUCCESS = 'DELETE_ORDER_BY_ID_SUCCESS'
export const DELETE_ORDER_BY_ID_FAIL = 'DELETE_ORDER_BY_ID_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST'
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL'
export const RESET_MY_ORDERS = 'RESET_MY_ORDERS'

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'

export const MARK_AS_DELIVERED_REQUEST = 'MARK_AS_DELIVERED_REQUEST'
export const MARK_AS_DELIVERED_SUCCESS = 'MARK_AS_DELIVERED_SUCCESS'
export const MARK_AS_DELIVERED_FAIL = 'MARK_AS_DELIVERED_FAIL'
