export const TOGGLE_SIDE_BAR_MENU_RIGHT = 'TOGGLE_SIDE_BAR_MENU_RIGHT'
export const CLOSE_SIDE_BAR_MENU_RIGHT = 'CLOSE_SIDE_BAR_MENU_RIGHT'
export const OPEN_SIDE_BAR_MENU_RIGHT = 'OPEN_SIDE_BAR_MENU_RIGHT'
